name = "Personalem"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = ""
homepage = "https://github.com/ashleycollinge1/Personalem"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Ashley Collinge"
  homepage = "ashleycollinge.co.uk"
[tableOfContents]
  endLevel = 3
  ordered = true
  startLevel = 2